notes Page
Code-the-Dream-School/ee-prac-team3-front pull request #13
Opened 2023-11-23 21:01 UTC by npnote8

Notes page
- searching
- sorting
- pagination
- no API calls
To view the page run "npm i" and go to http://localhost:3000/note
[NotesPageGit.pdf](https://github.com/Code-the-Dream-School/ee-prac-team3-front/files/13453416/NotesPageGit.pdf)

2023-11-25 04:01 UTC, in43sh requested changes
Great job, Alina! Other than a couple small things like code formatting and code style, I couldn't find much. Although there is a function `handleClick()` that I think is possible to refactor.

Also, there is some difference in how component files are called. Other files are using CamelCase, so for consistency reasons could you fix that?

Also, will it be possible to avoid using iconify by using mui icons?

I also noticed that this page is not responsive on mobile devices. Could you fix that? I've seen examples where it was done using horizontal scrolling.

Overall, really great job! I like that you used component propTypes feature and that you moved some functionality to the `utils.js` files. Also, your component structure for this page is well thought through.

2023-12-16 01:26 UTC, npnote8 commented on src/pages/Notes/notesPage.jsx
> +// import Scrollbar from "src/components/scrollbar";
removed Scrollbar

2023-12-16 01:28 UTC, npnote8 commented on src/pages/Notes/notesPage.jsx
> +// ----------------------------------------------------------------------
removed comment line

2023-12-16 01:28 UTC, npnote8 commented on src/pages/Notes/table-empty-rows.jsx
> +// ----------------------------------------------------------------------
removed comment line

2023-12-16 01:30 UTC, npnote8 commented on package.json
> +    "@iconify/react": "^4.1.1",
Used Material UI icons instead of Iconify

2023-12-16 01:30 UTC, npnote8 commented on src/pages/Notes/notesPage.jsx
> +  const handleSort = (event, id) => {
It has been used

2023-12-16 01:30 UTC, npnote8 commented on src/pages/Notes/notesPage.jsx
> +                  // { id: "" },
It has been used

2023-12-16 01:31 UTC, npnote8 commented on src/pages/Notes/notesPage.jsx
> +  const handleClick = (event, title) => {
For now I have no idea on how to refactor this function

2023-12-16 01:33 UTC, npnote8 commented on src/pages/Notes/notesPage.jsx
> +  const handleChangePage = (event, newPage) => {
It has been used

2023-12-17 13:02 UTC, ezbc approved these changes
Fantastic work Alina! This is a big feature and it looks awesome! 

There's some code refactoring suggestions but the feature functions well. I'll approve so that we can get this merged in time for the demo. Please take a look at my suggestions though so that you're aware for the future.

2023-12-17 13:02 UTC, ezbc commented on package.json
> +    "react-draggable": "^4.4.6",
I don't think this is used, is that correct? If so can you remove it?

2023-12-17 13:02 UTC, ezbc commented on src/functions/delete-notes.js
> +const useDelete = (ids) => {
Cool hook! I like it.

2023-12-17 13:02 UTC, ezbc commented on src/functions/fetch-notes.js
> +import { port } from 'App';
The filenaming convention in javascript is to use lower camel case. So `fetchNotes.js` instead of `fetch-notes.js`. Can you rename each of these files?

2023-12-17 13:02 UTC, ezbc commented on src/functions/delete-notes.js
> +const useDelete = (ids) => {
You know, I'm really liking having the API calls in separate hooks. I've often had one big context provider that exposes functions for each API call. I'm going to try this out in my own code!

2023-12-17 13:02 UTC, ezbc commented on src/pages/Notes/NoteForm.js
> +    validationSchema: Yup.object({
:fire:  way to use yup and formik!

2023-12-17 13:02 UTC, ezbc commented on src/pages/Notes/NoteForm.js
> +    if (response) {
The double conditional can be combined into:

```jsx
if (response?.success) {

}
```

The `?.` syntax will check if `response` is truthy, and if so, then proceed to the next step, getting the success attribute. If response is `falsey`, then the statement will stop executing.

2023-12-17 13:02 UTC, ezbc commented on src/pages/Notes/NoteForm.js
> +          <div>New Note</div>
Plain text is best represented in HTML with `<p>` tags. `<div>` tags don't have any semantic meaning and are meant to structure other tags in groups.

2023-12-17 13:02 UTC, ezbc commented on src/pages/Notes/table-head.jsx
> +export default function NotesTableHead({
I like that you split up the notes table into all these components! Make it much easier to read.

These components would be a great opportunity to use a notes context provider! The provider would help avoid passing all of these props down from the main notes page. You don't need to do this refactor, just a heads up for your future consideration.

2023-12-17 19:17 UTC, npnote8 commented on package.json
> +    "react-draggable": "^4.4.6",
Removed "react-draggable"

2023-12-17 19:18 UTC, npnote8 commented on src/functions/fetch-notes.js
> +import { port } from 'App';
renamed files according to the filenaming convention

2023-12-17 19:18 UTC, npnote8 commented on src/pages/Notes/NoteForm.js
> +    if (response) {
Tried, but didn't work

2023-12-17 19:19 UTC, npnote8 commented on src/pages/Notes/NoteForm.js
> +          <div>New Note</div>
replaced with <p> tags

2023-12-17 21:14 UTC, merged